### PR TITLE
Implement Burner role

### PR DESCRIPTION
**Pull request by merc1er**
> Remove previously faulty burn method which allowed totalSupply and user balance to be negative at any time to a new implemented Access Control over burn and burnFrom methods

- @aekasitt

### CODE REVIEW

**Comment by merc1er** [comment]
Why not allow anyone to burn tokens instead of having roles? That way the code would be simpler. And if people want to burn tokens we don't have any issues with that @aekasitt

**Comment by aekasitt** [comment]
Current implementation allows for anyone, holder or not, to have negative balances, and thus make total supply negative as well. More important than access control validation is the amount validation.

`burn` method has limited use cases and is not the focal point of the access control feature. More importantly than `burn` is`burnFrom` where admins have a way to deal with persona non grata. This requires admin access or burner role.

**Comment by merc1er** [comment]
> Current implementation allows for anyone, holder or not, to have negative balances

How is this the case? You can't burn more tokens than you have (unsigned integer does not allow negative).

**Comment by aekasitt** [comment]
You're right. Last I checked it caused an unsafe math reversion but a non-descriptive reversion message. Is the amount validation here costing too much gas?

**Comment by merc1er** [comment]
> You're right. Last I checked it caused an unsafe math reversion but a non-descriptive reversion message. Is the amount validation here costing too much gas?

I'm not sure what you are referring to. When trying to burn more than available, the transaction simply fails before even reaching the network. So there is no gas being spent.

Example, in an `ape console`:

```python
t = project.Token
contract = t.deployments[0]  # assuming your you deployed the contract previously
contract.burn(int(2000 * 1e8), sender=accounts[0])  # assuming accounts[0] has less than 2000 CAUD
```

This raises:

```shell
ContractLogicError: Transaction failed.
```

And no transaction is recorded in the block explorer ([example](https://ropsten.etherscan.io/token/0x7b7B0D664a6929521d189561F26dB4F77B8E18dd)).

I am not exactly sure where the exception is raised, or what the best practice is in this case. If the best practice is to check that `balance >= burn_amount`, then let's go ahead with that.

**Comment by merc1er** [comment]
@aekasitt I simplified this PR (#23) to simply add a check that the amount burnt does not exceed the sender's balance.

**Comment by merc1er** [comment]
I merged #23. Closing this for now. Can reopen if required.

**Pull request closed without merging**
